### ISSUE TITLE
"Store not found" will be displayed

### ISSUE THREAD

**Issue by nekoniii3** [SuryaSekhar14/vercel_blob#4]
"Store not found" or "Cannot get store id or token from authorization header" will be displayed.
"https://blob.vercel-storage.com" as the endpoint, do you have any details about this?

**Comment by SuryaSekhar14** [comment]
It would be helpful if you could provide the error in a format that is replicateable so that I can check the issue.

However, blob URLs are in the format "<store_id>.public.blob.vercel-storage.com", "blob.vercel-storage.com" is just the Base URL.

**Comment by nekoniii3** [comment]
We apologize for the inconvenience. I mistakenly thought it was a project token.

https://vercel.com/***********s-projects/~/stores/blob/store_************/browser
Get it here.

Thank you for your reply. We will close it.
